spring.datasource.url=jdbc:postgresql://ep-shiny-block-anjr3fqb-pooler.c-6.us-east-1.aws.neon.tech/instagramdb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yFT3k1fzBxHo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true