spring.datasource.url=jdbc:postgresql://ep-shiny-block-anjr3fqb-pooler.c-6.us-east-1.aws.neon.tech/instagramdb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yFT3k1fzBxHo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#cloud storage for posts and reels
cloudinary.cloud_name=domwuaypu
cloudinary.api_key=579163558879327
cloudinary.api_secret=oVUjNZW0BrTBi96a9cRU7wDNHg0

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Server Configuration for Multi-Machine WebSocket Support
server.address=0.0.0.0
server.port=8080
websocket.allowed-origins=*